### ISSUE TITLE
digest authentication

### ISSUE THREAD

**Issue by AvrumFeldman** [hbonath/sonicapi#1]
Hi,

I noticed you are explicitly mentioning that your module uses Basic authentication. 

If you are looking for a working example of **digest** authentication login, I implemented one using Powershell over [here](https://github.com/AvrumFeldman/PSSonicWall/blob/master/PSSonicWall/Private/Get-Digest.ps1). I don't know python but would happily help you out with whatever needed to port my code to python so it can be used in your script.

**Comment by hbonath** [comment]
Thanks for the heads-up. I have been able to put some more time into this and I looked into your solution.
Fortunately, I found that the [requests](https://github.com/psf/requests) module that I am using has a built-in method for [HTTPDigestAuth](https://github.com/psf/requests/blob/master/requests/auth.py#L108) that I was able to take advantage of.
I went ahead and switched that to be the default, allowing the option to revert to Basic if wanted.

I'm going to close this out as it is fixed in 396cc9b3ddb52c3ca6127e5a62476dd8d8a9f48a
